name: Update README.md with current date

on:
  push:
    branches:
      - main
  workflow_dispatch:  # Allows manual trigger

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v2

    - name: Set up R
      uses: r-lib/actions/setup-r@v2

    - name: Install required R packages
      run: |
        install.packages("stringr")

    - name: Run the R script to update README.md
      run: |
        Rscript update_readme.R

    - name: Commit and push the updated README.md
      run: |
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git config --global user.name "github-actions[bot]"
        git add README.md
        git commit -m "Update README.md with the latest date"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
