name: Update README

on:
  push:
    branches:
      - main

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Git
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "actions@github.com"

      - name: Replace Last Updated placeholder
        run: |
          # Replace <!--LAST_UPDATED--> with the current date (in YYYY-MM-DD format)
          CURRENT_DATE=$(date +'%Y-%m-%d')
          sed -i "s|<!--LAST_UPDATED-->|$CURRENT_DATE|" README.md

      - name: Commit changes to README.md
        run: |
          git add README.md
          git commit -m "Update README.md with latest changes"
          git push
